# This file is copied from sigs.k8s.io/cluster-api/config/default/
# so that we can override the manager image patch file.
# We need to ensure this kustomize config matches
# the config in sigs.k8s.io/cluster-api/config/default/kustomization.yaml

# Adds namespace to all resources.
namespace: cluster-api-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: cluster-api-

bases:
- ../../vendor/sigs.k8s.io/cluster-api/config/crds/
- ../../vendor/sigs.k8s.io/cluster-api/config/rbac/
- ../../vendor/sigs.k8s.io/cluster-api/config/manager/

patches:
- manager_image_patch.yaml
